//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the robotnik_pp_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __robotnik_pp_planner__ROBOTNIK_PP_PLANNERCONFIG_H__
#define __robotnik_pp_planner__ROBOTNIK_PP_PLANNERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace robotnik_pp_planner
{
  class robotnik_pp_plannerConfigStatics;

  class robotnik_pp_plannerConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(robotnik_pp_plannerConfig &config, const robotnik_pp_plannerConfig &max, const robotnik_pp_plannerConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const robotnik_pp_plannerConfig &config1, const robotnik_pp_plannerConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, robotnik_pp_plannerConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const robotnik_pp_plannerConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, robotnik_pp_plannerConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const robotnik_pp_plannerConfig &config) const = 0;
      virtual void getValue(const robotnik_pp_plannerConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T robotnik_pp_plannerConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (robotnik_pp_plannerConfig::* field);

      virtual void clamp(robotnik_pp_plannerConfig &config, const robotnik_pp_plannerConfig &max, const robotnik_pp_plannerConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const robotnik_pp_plannerConfig &config1, const robotnik_pp_plannerConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, robotnik_pp_plannerConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const robotnik_pp_plannerConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, robotnik_pp_plannerConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const robotnik_pp_plannerConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const robotnik_pp_plannerConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, robotnik_pp_plannerConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, robotnik_pp_plannerConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(robotnik_pp_plannerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class PID
{
  public:
    PID()
    {
      state = true;
      name = "PID";
    }

    void setParams(robotnik_pp_plannerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_w"==(*_i)->name){max_w = boost::any_cast<double>(val);}
        if("min_w"==(*_i)->name){min_w = boost::any_cast<double>(val);}
        if("kp_w"==(*_i)->name){kp_w = boost::any_cast<double>(val);}
        if("ki_w"==(*_i)->name){ki_w = boost::any_cast<double>(val);}
        if("kd_w"==(*_i)->name){kd_w = boost::any_cast<double>(val);}
        if("max_v"==(*_i)->name){max_v = boost::any_cast<double>(val);}
        if("min_v"==(*_i)->name){min_v = boost::any_cast<double>(val);}
        if("kp_v"==(*_i)->name){kp_v = boost::any_cast<double>(val);}
        if("ki_v"==(*_i)->name){ki_v = boost::any_cast<double>(val);}
        if("kd_v"==(*_i)->name){kd_v = boost::any_cast<double>(val);}
      }
    }

    double max_w;
double min_w;
double kp_w;
double ki_w;
double kd_w;
double max_v;
double min_v;
double kp_v;
double ki_v;
double kd_v;

    bool state;
    std::string name;

    
}pid;

class TRAJECTORYCONTROL
{
  public:
    TRAJECTORYCONTROL()
    {
      state = true;
      name = "TrajectoryControl";
    }

    void setParams(robotnik_pp_plannerConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("look_ahead_inc"==(*_i)->name){look_ahead_inc = boost::any_cast<double>(val);}
        if("d_lookahear_min"==(*_i)->name){d_lookahear_min = boost::any_cast<double>(val);}
        if("d_lookahear_max"==(*_i)->name){d_lookahear_max = boost::any_cast<double>(val);}
        if("max_speed"==(*_i)->name){max_speed = boost::any_cast<double>(val);}
        if("desired_freq"==(*_i)->name){desired_freq = boost::any_cast<double>(val);}
      }
    }

    double look_ahead_inc;
double d_lookahear_min;
double d_lookahear_max;
double max_speed;
double desired_freq;

    bool state;
    std::string name;

    
}trajectorycontrol;

}groups;



//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double max_w;
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double min_w;
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double kp_w;
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double ki_w;
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double kd_w;
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double max_v;
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double min_v;
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double kp_v;
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double ki_v;
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double kd_v;
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double look_ahead_inc;
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double d_lookahear_min;
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double d_lookahear_max;
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double max_speed;
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      double desired_freq;
//#line 228 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("robotnik_pp_plannerConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const robotnik_pp_plannerConfig &__max__ = __getMax__();
      const robotnik_pp_plannerConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const robotnik_pp_plannerConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const robotnik_pp_plannerConfig &__getDefault__();
    static const robotnik_pp_plannerConfig &__getMax__();
    static const robotnik_pp_plannerConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const robotnik_pp_plannerConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void robotnik_pp_plannerConfig::ParamDescription<std::string>::clamp(robotnik_pp_plannerConfig &config, const robotnik_pp_plannerConfig &max, const robotnik_pp_plannerConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class robotnik_pp_plannerConfigStatics
  {
    friend class robotnik_pp_plannerConfig;

    robotnik_pp_plannerConfigStatics()
    {
robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT, robotnik_pp_plannerConfig> Default("Default", "", 0, 0, true, &robotnik_pp_plannerConfig::groups);
robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::PID, robotnik_pp_plannerConfig::DEFAULT> PID("PID", "", 0, 1, true, &robotnik_pp_plannerConfig::DEFAULT::pid);
//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.max_w = 0.0;
//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.max_w = 6.28318530718;
//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.max_w = 3.14159265359;
//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_w", "double", 0, "max rotate speed", "", &robotnik_pp_plannerConfig::max_w)));
//#line 13 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_w", "double", 0, "max rotate speed", "", &robotnik_pp_plannerConfig::max_w)));
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.min_w = -3.14159265359;
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.min_w = 1.57079632679;
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.min_w = -3.14159265359;
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("min_w", "double", 0, "min rotate speed", "", &robotnik_pp_plannerConfig::min_w)));
//#line 14 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("min_w", "double", 0, "min rotate speed", "", &robotnik_pp_plannerConfig::min_w)));
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.kp_w = 0.0;
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.kp_w = 2.0;
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.kp_w = 0.5;
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kp_w", "double", 0, "kp for rotate speed", "", &robotnik_pp_plannerConfig::kp_w)));
//#line 15 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kp_w", "double", 0, "kp for rotate speed", "", &robotnik_pp_plannerConfig::kp_w)));
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.ki_w = 0.0;
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.ki_w = 0.5;
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.ki_w = 0.05;
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("ki_w", "double", 0, "ki for rotate speed", "", &robotnik_pp_plannerConfig::ki_w)));
//#line 16 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("ki_w", "double", 0, "ki for rotate speed", "", &robotnik_pp_plannerConfig::ki_w)));
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.kd_w = 0.0;
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.kd_w = 0.5;
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.kd_w = 0.005;
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kd_w", "double", 0, "kd for rotate speed", "", &robotnik_pp_plannerConfig::kd_w)));
//#line 17 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kd_w", "double", 0, "kd for rotate speed", "", &robotnik_pp_plannerConfig::kd_w)));
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.max_v = 0.0;
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.max_v = 2.0;
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.max_v = 1.0;
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_v", "double", 0, "max translate speed", "", &robotnik_pp_plannerConfig::max_v)));
//#line 19 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_v", "double", 0, "max translate speed", "", &robotnik_pp_plannerConfig::max_v)));
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.min_v = 0.0;
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.min_v = 0.1;
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.min_v = 0.0;
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("min_v", "double", 0, "min translate speed", "", &robotnik_pp_plannerConfig::min_v)));
//#line 20 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("min_v", "double", 0, "min translate speed", "", &robotnik_pp_plannerConfig::min_v)));
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.kp_v = 0.0;
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.kp_v = 2.0;
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.kp_v = 0.5;
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kp_v", "double", 0, "kp for translate speed", "", &robotnik_pp_plannerConfig::kp_v)));
//#line 21 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kp_v", "double", 0, "kp for translate speed", "", &robotnik_pp_plannerConfig::kp_v)));
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.ki_v = 0.0;
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.ki_v = 0.5;
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.ki_v = 0.05;
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("ki_v", "double", 0, "ki for translate speed", "", &robotnik_pp_plannerConfig::ki_v)));
//#line 22 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("ki_v", "double", 0, "ki for translate speed", "", &robotnik_pp_plannerConfig::ki_v)));
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.kd_v = 0.0;
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.kd_v = 0.5;
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.kd_v = 0.005;
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      PID.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kd_v", "double", 0, "kd for translate speed", "", &robotnik_pp_plannerConfig::kd_v)));
//#line 23 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("kd_v", "double", 0, "kd for translate speed", "", &robotnik_pp_plannerConfig::kd_v)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      PID.convertParams();
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr(new robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::PID, robotnik_pp_plannerConfig::DEFAULT>(PID)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr(new robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::PID, robotnik_pp_plannerConfig::DEFAULT>(PID)));
robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::TRAJECTORYCONTROL, robotnik_pp_plannerConfig::DEFAULT> TrajectoryControl("TrajectoryControl", "", 0, 2, true, &robotnik_pp_plannerConfig::DEFAULT::trajectorycontrol);
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.look_ahead_inc = 0.001;
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.look_ahead_inc = 0.3;
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.look_ahead_inc = 0.05;
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      TrajectoryControl.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("look_ahead_inc", "double", 0, "trajectory track inc dist", "", &robotnik_pp_plannerConfig::look_ahead_inc)));
//#line 27 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("look_ahead_inc", "double", 0, "trajectory track inc dist", "", &robotnik_pp_plannerConfig::look_ahead_inc)));
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.d_lookahear_min = 0.05;
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.d_lookahear_min = 1.0;
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.d_lookahear_min = 0.3;
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      TrajectoryControl.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("d_lookahear_min", "double", 0, "trajectory track min dist", "", &robotnik_pp_plannerConfig::d_lookahear_min)));
//#line 28 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("d_lookahear_min", "double", 0, "trajectory track min dist", "", &robotnik_pp_plannerConfig::d_lookahear_min)));
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.d_lookahear_max = 1.0;
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.d_lookahear_max = 2.0;
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.d_lookahear_max = 1.1;
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      TrajectoryControl.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("d_lookahear_max", "double", 0, "trajectory track max dist", "", &robotnik_pp_plannerConfig::d_lookahear_max)));
//#line 29 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("d_lookahear_max", "double", 0, "trajectory track max dist", "", &robotnik_pp_plannerConfig::d_lookahear_max)));
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.max_speed = 1.0;
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.max_speed = 2.0;
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.max_speed = 1.2;
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      TrajectoryControl.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_speed", "double", 0, "trajectory track max speed", "", &robotnik_pp_plannerConfig::max_speed)));
//#line 30 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("max_speed", "double", 0, "trajectory track max speed", "", &robotnik_pp_plannerConfig::max_speed)));
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __min__.desired_freq = 10.0;
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __max__.desired_freq = 100.0;
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __default__.desired_freq = 50.0;
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      TrajectoryControl.abstract_parameters.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("desired_freq", "double", 0, "trajectory track frequency", "", &robotnik_pp_plannerConfig::desired_freq)));
//#line 31 "/home/hdros/catkin_ws/src/robotnik_purepursuit_planner-master/robotnik_pp_planner/cfg/robotnik_pp_planner.cfg"
      __param_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr(new robotnik_pp_plannerConfig::ParamDescription<double>("desired_freq", "double", 0, "trajectory track frequency", "", &robotnik_pp_plannerConfig::desired_freq)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      TrajectoryControl.convertParams();
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr(new robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::TRAJECTORYCONTROL, robotnik_pp_plannerConfig::DEFAULT>(TrajectoryControl)));
//#line 123 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr(new robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT::TRAJECTORYCONTROL, robotnik_pp_plannerConfig::DEFAULT>(TrajectoryControl)));
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr(new robotnik_pp_plannerConfig::GroupDescription<robotnik_pp_plannerConfig::DEFAULT, robotnik_pp_plannerConfig>(Default)));
//#line 366 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    robotnik_pp_plannerConfig __max__;
    robotnik_pp_plannerConfig __min__;
    robotnik_pp_plannerConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const robotnik_pp_plannerConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static robotnik_pp_plannerConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &robotnik_pp_plannerConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const robotnik_pp_plannerConfig &robotnik_pp_plannerConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const robotnik_pp_plannerConfig &robotnik_pp_plannerConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const robotnik_pp_plannerConfig &robotnik_pp_plannerConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<robotnik_pp_plannerConfig::AbstractParamDescriptionConstPtr> &robotnik_pp_plannerConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<robotnik_pp_plannerConfig::AbstractGroupDescriptionConstPtr> &robotnik_pp_plannerConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const robotnik_pp_plannerConfigStatics *robotnik_pp_plannerConfig::__get_statics__()
  {
    const static robotnik_pp_plannerConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = robotnik_pp_plannerConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROBOTNIK_PP_PLANNERRECONFIGURATOR_H__
