<?xml version="1.0"?>

<robot name="ackermann_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ackermann_controller)/test/urdf_houdar/chassis.xacro" />
  <xacro:include filename="$(find ackermann_controller)/test/urdf_houdar/wheel_steered.xacro" />

  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Wheel Mounting Positions -->
  <xacro:property name="ground_clearance" value="0.19" />
  <!--  offset dist bet 4 wheel center and  body box center (wheel base(dist bet fr and re wheel) is fixed) chq -->
  <xacro:property name="wheel_x_offset" value="0.0" />
  <!--  offset dist bet steer box  and  corresponding steer_wheel ( track(dist bet l and r wheel) is fixed ) 
    the greater the wheel_y_offset,
    the further the dist bet steer_box and steer_wheel,
    the closer the dist bet steer box cord and base_link cord in Y axis chq 
   -->
  <xacro:property name="wheel_y_offset" value="0.05" />

  <xacro:chassis/>
 <!-- -  -|car rear_right
   |      |
   |      |
   |      |
   |______|front_right-->

  <!-- Wheel macros -->
  <!-- steer left wheel -->
  <xacro:wheel_steered wheel_prefix="front_left" parent_link="base_link" wheel_origin_y="${wheel_y_offset}" left_right="-1">
    <origin xyz="${wheelbase/2+wheel_x_offset} ${-wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
  </xacro:wheel_steered>

  <!-- steer right wheel -->
 <!--xacro:wheel_steered wheel_prefix="front_right" parent_link="base_link" wheel_origin_y="${-wheel_y_offset}" left_right="1">
   <origin xyz="${wheelbase/2+wheel_x_offset} ${-track/2+wheel_y_offset} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
  </xacro:wheel_steered-->
 

<!-- relative dist bet rear left wheel cord and base_link cord in XYZ chq -->
  <xacro:wheel wheel_prefix="rear_left" parent_link="base_link" left_right="-1">
    <origin xyz="${-wheelbase/2+wheel_x_offset} ${track/2} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
  </xacro:wheel>


  <xacro:wheel wheel_prefix="rear_right" parent_link="base_link" left_right="1">
    <origin xyz="${-wheelbase/2+wheel_x_offset} ${-track/2} ${-base_z_size/2 + wheel_radius - ground_clearance}" rpy="0 0 0" />
  </xacro:wheel>

<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
  <robotNamespace>/</robotNamespace>
  </plugin>
</gazebo>

</robot>
