local_costmap:
   global_frame: odom
   robot_base_frame: /base_link
   update_frequency: 5.0 #Hz 
   publish_frequency: 1.0 #Hz 
   static_map: false
   rolling_window: true
   width: 5.0
   height: 5.0
   resolution: 0.05
   transform_tolerance: 1
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}