# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
#move_base node para
shutdown_costmaps: false
#The rate in Hz at which to run the control loop and send velocity commands to the base
controller_frequency: 5.0
controller_patience: 3.0

#The rate in Hz at which to run the global planning loop. If the frequency is set to 0.0, 
#the global planner will only run when a new goal is received or the local planner reports that its path is blocked
planner_frequency: 3.0
planner_patience: 5.0

oscillation_timeout: 10.0
#How far in meters the robot must move to be considered not to be oscillating
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
# base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_local_planner: "eband_local_planner/EBandPlannerROS"
# base_local_planner: "teb_local_planner/TebLocalPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner


#We plan to integrate recovery behaviors for turtlebot but currently those belong to gopher and still have to be adapted.
## recovery behaviors; we avoid spinning, but we need a fall-back replanning
#recovery_behavior_enabled: true

#recovery_behaviors:
  #- name: 'super_conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation1'
    #type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
    #type: 'rotate_recovery/RotateRecovery'

#super_conservative_reset1:
  #reset_distance: 3.0
#conservative_reset1:
  #reset_distance: 1.5
#aggressive_reset1:
  #reset_distance: 0.0
#super_conservative_reset2:
  #reset_distance: 3.0
#conservative_reset2:
  #reset_distance: 1.5
#aggressive_reset2:
  #reset_distance: 0.0
