local_costmap:
 global_frame: odom
 robot_base_frame: base_link
 inscribed_radius: 0.5
 circumscribed_radius: 0.6
 #The frequency in Hz for the map to be updated.
 update_frequency: 5.0
 #The frequency in Hz for the map to be publish display information.
 publish_frequency: 3.0
 static_map: true
#if enable rolling window to keep the robot to be center
 rolling_window: true
#cost map size  
#The width of the map in meters.
 width: 3.0
 height: 2.0
#unit=m
#The resolution of the map in meters/cell.
 resolution: 0.05
 #Specifies the delay in transform (tf) data that is tolerable in seconds
 transform_tolerance: 1
 plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}